export const FAKE_TAGS = [
	{ id: '1', name: 'Tag 1' },
	{ id: '2', name: 'Tag 2' },
	{ id: '3', name: 'Tag 3' },
	{ id: '4', name: 'Tag 4' },
	{ id: '5', name: 'Tag 5' },
	{ id: '6', name: 'Tag 6' },
	{ id: '7', name: 'Tag 7' },
	{ id: '8', name: 'Tag 8' },
	{ id: '9', name: 'Tag 9' },
	{ id: '10', name: 'Tag 10' },
	{ id: '11', name: 'Tag 11' },
	{ id: '12', name: 'Tag 12' },
	{ id: '13', name: 'Tag 13' },
	{ id: '14', name: 'Tag 14' },
	{ id: '15', name: 'Tag 15' },
	{ id: '16', name: 'Tag 16' },
	{ id: '17', name: 'Tag 17' },
	{ id: '18', name: 'Tag 18' },
	{ id: '19', name: 'Tag 19' },
];
