export const FAKE_USERS = [
	{
		id: 1,
		name: 'Leanne Graham',
		username: 'Bret',
		firstname: 'Bret',
		lastname: 'Bret',
		surname: 'Bret',
		email: 'Sincere@april.biz',
		phone: '1-770-736-8031 x56442',
		website: 'hildegard.org',
    role: 'Administrator'
	},
	{
		id: 2,
		name: 'Ervin Howell',
		username: 'Antonette',
		firstname: 'Antonette',
		lastname: 'Antonette',
		surname: 'Antonette',
		email: 'Shanna@melissa.tv',
		phone: '010-692-6593 x09125',
		website: 'anastasia.net',
    role: 'Manager'
	},
	{
		id: 3,
		name: 'Clementine Bauch',
		username: 'Samantha',
		firstname: 'Samantha',
		lastname: 'Samantha',
		surname: 'Samantha',
		email: 'Nathan@yesenia.net',
		phone: '1-463-123-4447',
		website: 'ramiro.info',
    role: 'Quest'
	},
	{
		id: 4,
		name: 'Patricia Lebsack',
		username: 'Karianne',
		firstname: 'Karianne',
		lastname: 'Karianne',
		surname: 'Karianne',
		email: 'Julianne.OConner@kory.org',
		phone: '493-170-9623 x156',
		website: 'kale.biz',
    role: 'Quest'
	},
	{
		id: 5,
		name: 'Chelsey Dietrich',
		username: 'Kamren',
		firstname: 'Kamren',
		lastname: 'Kamren',
		surname: 'Kamren',
		email: 'Lucio_Hettinger@annie.ca',
		phone: '(254)954-1289',
		website: 'demarco.info',
    role: 'Quest'
	},
	{
		id: 6,
		name: 'Mrs. Dennis Schulist',
		username: 'Leopoldo_Corkery',
		firstname: 'Leopoldo_Corkery',
		lastname: 'Leopoldo_Corkery',
		surname: 'Leopoldo_Corkery',
		email: 'Karley_Dach@jasper.info',
		phone: '1-477-935-8478 x6430',
		website: 'ola.org',
    role: 'Director'
	},
	{
		id: 7,
		name: 'Kurtis Weissnat',
		username: 'Elwyn.Skiles',
		firstname: 'Elwyn.Skiles',
		lastname: 'Elwyn.Skiles',
		surname: 'Elwyn.Skiles',
		email: 'Telly.Hoeger@billy.biz',
		phone: '210.067.6132',
		website: 'elvis.io',
    role: 'Manager'
	},
	{
		id: 8,
		name: 'Nicholas Runolfsdottir V',
		username: 'Maxime_Nienow',
		firstname: 'Maxime_Nienow',
		lastname: 'Maxime_Nienow',
		surname: 'Maxime_Nienow',
		email: 'Sherwood@rosamond.me',
		phone: '586.493.6943 x140',
		website: 'jacynthe.com',
    role: 'Quest'
	},
	{
		id: 9,
		name: 'Glenna Reichert',
		username: 'Delphine',
		firstname: 'Delphine',
		lastname: 'Delphine',
		surname: 'Delphine',
		email: 'Chaim_McDermott@dana.io',
		phone: '(775)976-6794 x41206',
		website: 'conrad.com',
    role: 'Quest'
	},
	{
		id: 10,
		name: 'Clementina DuBuque',
		username: 'Moriah.Stanton',
		firstname: 'Moriah.Stanton',
		lastname: 'Moriah.Stanton',
		surname: 'Moriah.Stanton',
		email: 'Rey.Padberg@karina.biz',
		phone: '024-648-3804',
		website: 'ambrose.net',
    role: 'Quest'
	},
];
